"""Add status to Installment model

Revision ID: 30e2d1daac1b
Revises: 948737fd3bd4
Create Date: 2024-11-16 18:51:41.147510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e2d1daac1b'
down_revision: Union[str, None] = '948737fd3bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installment', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installment', 'status')
    # ### end Alembic commands ###
