"""Added Payement_History Table

Revision ID: 948737fd3bd4
Revises: f134263f87c2
Create Date: 2024-11-16 16:44:00.849538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948737fd3bd4'
down_revision: Union[str, None] = 'f134263f87c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('paid_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_history')
    # ### end Alembic commands ###
