"""Created database and it's structure

Revision ID: ab0e310b4c9f
Revises: 
Create Date: 2024-11-13 16:36:54.412341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0e310b4c9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institute_name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('created_time', sa.Time(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('institute_name'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_duration', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('institute_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['institute_name'], ['users.institute_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_contact', sa.String(length=15), nullable=False),
    sa.Column('student_mail', sa.String(length=100), nullable=False),
    sa.Column('student_address', sa.String(length=255), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('total_payable_amnt', sa.Float(), nullable=False),
    sa.Column('institute_name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_details.id'], ),
    sa.ForeignKeyConstraint(['institute_name'], ['users.institute_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_mail')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_details')
    op.drop_table('course_details')
    op.drop_table('users')
    # ### end Alembic commands ###
